import { useNavigate } from "react-router-dom";
import { gallery_images } from "../../data";
import { motion } from "framer-motion";
import { ArrowLeft, Copy, Zap, Sparkles } from "lucide-react";
import "./showcase.css";
import toast from "react-hot-toast";

const Showcase = () => {
  const navigate = useNavigate();

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    toast.success("Prompt copied to clipboard!");
  };

  return (
    <div className="showcase-page min-h-screen bg-black text-white selection:bg-purple-500/30">
      {/* Background Blobs */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-purple-600/10 blur-[120px] rounded-full"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-600/10 blur-[120px] rounded-full"></div>
      </div>

      {/* Header */}
      <header className="z-20 px-6 py-8 border-b border-white/5 backdrop-blur-md bg-black/50 sticky top-0">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors group"
          >
            <ArrowLeft
              size={20}
              className="group-hover:-translate-x-1 transition-transform"
            />
            <span className="font-bold uppercase tracking-widest text-xs">
              Back to Home
            </span>
          </button>

          <div className="text-center hidden md:block">
            <h1 className="text-xl font-black bg-gradient-to-r from-purple-500 to-blue-500 bg-clip-text text-transparent">
              IMAGIUR SHOWCASE
            </h1>
          </div>

          <button
            onClick={() => navigate("/dashboard/image-generate")}
            className="px-6 py-2 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full text-xs font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all shadow-lg shadow-purple-500/20"
          >
            Generate Mine
          </button>
        </div>
      </header>

      <main className="relative z-10 px-6 py-16 max-w-7xl mx-auto">
        <div className="mb-16 text-center md:text-left">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-[0.2em] text-purple-400 mb-6"
          >
            <Sparkles size={12} /> Community Creations
          </motion.div>
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-6xl font-black mb-6 tracking-tight"
          >
            The Art of <span className="text-purple-500">Possible</span>
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-gray-400 max-w-2xl text-lg font-medium leading-relaxed"
          >
            Explore a curated collection of stunning visuals generated by the
            Imagiur community. Click on any image to copy its prompt and start
            experimenting.
          </motion.p>
        </div>

        {/* Masonry Grid - Multi-column stack approach */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {[0, 1, 2, 3].map((colIndex) => (
            <div
              key={colIndex}
              className={`flex flex-col gap-8 ${
                colIndex === 1
                  ? "hidden md:flex"
                  : colIndex === 2
                    ? "hidden lg:flex"
                    : colIndex === 3
                      ? "hidden xl:flex"
                      : ""
              }`}
            >
              {gallery_images
                .filter((_, index) => {
                  // Logic to distribute images across active columns based on screen size
                  // For simplicity and stability, we use a fixed modulo but hide columns
                  return index % 4 === colIndex;
                })
                .map((item, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, scale: 0.9 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.1 }}
                    className="relative group overflow-hidden rounded-3xl border border-white/5 bg-white/[0.02] shadow-2xl"
                  >
                    <img
                      src={item.img}
                      alt={item.prompt}
                      className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-105"
                    />

                    <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 p-6 flex flex-col justify-end">
                      <div className="flex items-center justify-between gap-4">
                        <div className="flex-1 overflow-hidden">
                          <p className="text-[10px] font-black text-purple-400 uppercase tracking-widest mb-1">
                            PROMPT
                          </p>
                          <p className="text-sm font-bold truncate">
                            {item.prompt}
                          </p>
                        </div>
                        <button
                          onClick={() => copyToClipboard(item.prompt)}
                          className="p-3 rounded-full bg-white/10 hover:bg-white/20 border border-white/10 backdrop-blur-md transition-all active:scale-90 flex-shrink-0"
                          title="Copy Prompt"
                        >
                          <Copy size={16} />
                        </button>
                      </div>

                      <button
                        onClick={() =>
                          navigate("/dashboard/image-generate", {
                            state: { prompt: item.prompt },
                          })
                        }
                        className="mt-4 w-full py-3 bg-white text-black rounded-2xl font-black text-[10px] uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-purple-500 hover:text-white transition-all transform translate-y-4 group-hover:translate-y-0"
                      >
                        <Zap size={14} className="fill-current" /> Remix This
                      </button>
                    </div>
                  </motion.div>
                ))}
            </div>
          ))}
        </div>
      </main>

      {/* Footer CTA */}
      <section className="py-32 px-6 border-t border-white/5 mt-20 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-px bg-gradient-to-r from-transparent via-purple-500/50 to-transparent" />
        <div className="max-w-4xl mx-auto text-center">
          <h3 className="text-3xl md:text-5xl font-black mb-8 leading-tight">
            Ready to create your <br /> next masterpiece?
          </h3>
          <button
            onClick={() => navigate("/dashboard/image-generate")}
            className="px-12 py-5 bg-gradient-to-r from-purple-600 to-blue-600 rounded-2xl font-black text-sm uppercase tracking-widest hover:scale-105 transition-all shadow-2xl shadow-purple-500/40"
          >
            Get Started for Free
          </button>
        </div>
      </section>
    </div>
  );
};

export default Showcase;
